% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 17-May-2017 10:29:44
%
% This script assumes these variables are defined:
%
%   data - input data.

x = csvread("datasets/glioma-daumas-duport.csv", 1, 0)';

% Create a Self-Organizing Map
dimension1 = 20;
dimension2 = 20;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,x);

% Test the Network
y = net(x);

% View the Network
%view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,x)
%figure, plotsompos(net,x)

